name:                math-programming-tests
version:             0.2.0
github:              "prsteele/math-programming-tests"
license:             BSD3
author:              "Patrick Steele"
maintainer:          "steele.pat@gmail.com"
copyright:           "2018 Patrick Steele"

# Metadata used when publishing your package
synopsis:            Utility functions for testing implementations of the math-programming library.
category:            Math

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/prsteele/math-programming-api-tests#readme>

dependencies:
  - base >= 4.7 && < 5
  - math-programming >= 0.2.0 && < 0.3
  - tasty >= 1.2 && < 1.3
  - tasty-hunit >= 0.10.0.1 && < 0.11
  - tasty-quickcheck >= 0.10 && < 0.11

library:
  source-dirs: src
  ghc-options:
    - -Wall
