name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: prsteele/stack-build-glpk:v1-8.6.5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: stack --allow-different-user test --pedantic
